# Generated by Django 4.1.1 on 2022-09-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('age', models.PositiveSmallIntegerField(verbose_name='age')),
                ('residence', models.CharField(max_length=255, verbose_name='residence')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.PositiveIntegerField(verbose_name='phone')),
                ('address', models.TextField(verbose_name='address')),
                ('profile_image', models.ImageField(upload_to='owner_pic', verbose_name='profile pic')),
                ('about_me', models.TextField(verbose_name='about me')),
            ],
            options={
                'verbose_name': 'owner',
                'verbose_name_plural': 'owners',
            },
        ),
    ]
