# Generated by Django 4.1.1 on 2022-09-14 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255, verbose_name='field')),
                ('detail', models.CharField(max_length=255, verbose_name='detail')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certificate', verbose_name='certificate logo')),
                ('certified_date', models.DateField(verbose_name='certified date')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='who suggest owner?')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client_logo', verbose_name='client logo')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerExpertAt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='owner expert at: ')),
                ('detail', models.TextField(verbose_name='detail')),
                ('html_icon_class', models.CharField(max_length=255, verbose_name='html icon class - example: lnr lnr-pencil')),
                ('order', models.PositiveSmallIntegerField(verbose_name='ordering')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='owner knowledge')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerResumeSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, verbose_name='who suggest owner?')),
                ('detail', models.TextField(verbose_name='detail')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='subject')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='owner',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='owner',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='linkedin'),
        ),
        migrations.AddField(
            model_name='owner',
            name='main_expertise',
            field=models.CharField(default=1, max_length=255, verbose_name='main expertise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='pdf_cv',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='CV.pdf'),
        ),
        migrations.AddField(
            model_name='owner',
            name='tweeter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tweeter'),
        ),
        migrations.AddField(
            model_name='owner',
            name='youtube',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='youtube'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='about me'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='owner_pic', verbose_name='profile pic'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='residence',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='residence'),
        ),
        migrations.CreateModel(
            name='OwnerExperienceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_year', models.CharField(max_length=255, verbose_name='starting_year')),
                ('ending_year', models.CharField(max_length=255, verbose_name='ending_year')),
                ('the_place', models.CharField(max_length=255, verbose_name='the_place')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('content', models.TextField(verbose_name='content')),
                ('owner_resume_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.ownerresumesubject')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_certificate',
            field=models.ManyToManyField(to='owner.ownercertificate'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_client',
            field=models.ManyToManyField(to='owner.ownerclient'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_experience_detail',
            field=models.ManyToManyField(to='owner.ownerexperiencedetail'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_expert_at',
            field=models.ManyToManyField(to='owner.ownerexpertat'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_knowledge',
            field=models.ManyToManyField(to='owner.ownerknowledge'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_testimonial',
            field=models.ManyToManyField(to='owner.ownertestimonial'),
        ),
    ]
