# Generated by Django 4.1.1 on 2022-09-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_alter_owner_owner_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerclient',
            name='name',
            field=models.CharField(max_length=255, verbose_name="owner's client"),
        ),
        migrations.AlterField(
            model_name='ownerexperiencedetail',
            name='ending_year',
            field=models.CharField(max_length=255, verbose_name='ending year'),
        ),
        migrations.AlterField(
            model_name='ownerexperiencedetail',
            name='starting_year',
            field=models.CharField(max_length=255, verbose_name='starting year'),
        ),
        migrations.AlterField(
            model_name='ownerexperiencedetail',
            name='the_place',
            field=models.CharField(max_length=255, verbose_name='the place'),
        ),
    ]
