# Generated by Django 4.1.1 on 2022-09-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_alter_ownerclient_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'owner', 'verbose_name_plural': 'owner'},
        ),
        migrations.RenameField(
            model_name='ownercertificate',
            old_name='field',
            new_name='certify_by',
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_certificate',
            field=models.ManyToManyField(blank=True, to='owner.ownercertificate', verbose_name='owner certificate'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_client',
            field=models.ManyToManyField(blank=True, to='owner.ownerclient', verbose_name='owner client'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_experience_detail',
            field=models.ManyToManyField(blank=True, to='owner.ownerexperiencedetail', verbose_name='owner experience detail'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_expert_at',
            field=models.ManyToManyField(blank=True, to='owner.ownerexpertat', verbose_name='owner expert at'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_knowledge',
            field=models.ManyToManyField(blank=True, to='owner.ownerknowledge', verbose_name='owner knowledge'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_testimonial',
            field=models.ManyToManyField(blank=True, to='owner.ownertestimonial', verbose_name='owner testimonial'),
        ),
    ]
