# Generated by Django 4.1.1 on 2022-09-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_alter_owner_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownercertificate',
            name='certify_by',
            field=models.CharField(max_length=255, verbose_name='certified by'),
        ),
        migrations.AlterField(
            model_name='ownercertificate',
            name='logo',
            field=models.ImageField(blank=True, default='default_logo.png', upload_to='certificate', verbose_name='certificate logo'),
        ),
        migrations.AlterField(
            model_name='ownerclient',
            name='logo',
            field=models.ImageField(blank=True, default='default_logo.png', upload_to='client_logo', verbose_name='client logo'),
        ),
    ]
