# Generated by Django 4.1.1 on 2022-09-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_alter_ownercertificate_certify_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='tweeter',
            new_name='twitter',
        ),
        migrations.AlterField(
            model_name='owner',
            name='profile_image',
            field=models.ImageField(blank=True, default='main_photo.png', null=True, upload_to='owner_pic', verbose_name='profile pic'),
        ),
    ]
