# Generated by Django 4.1.1 on 2022-09-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_ownertestimonial_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerclient',
            name='website_link',
            field=models.URLField(blank=True, null=True, verbose_name='client website link'),
        ),
    ]
