# Generated by Django 4.1.1 on 2022-09-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_ownerclient_website_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owner_resume_subject',
            field=models.ManyToManyField(blank=True, to='owner.ownerresumesubject', verbose_name='owner resume subject'),
        ),
        migrations.AlterField(
            model_name='ownerclient',
            name='name',
            field=models.CharField(max_length=255, verbose_name='client name'),
        ),
    ]
