# Generated by Django 4.1.1 on 2022-09-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0011_owner_owner_resume_subject_alter_ownerclient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owner_experience_detail',
        ),
        migrations.RemoveField(
            model_name='ownerexperiencedetail',
            name='owner_resume_subject',
        ),
        migrations.AddField(
            model_name='ownerresumesubject',
            name='owner_experience_detail',
            field=models.ManyToManyField(blank=True, to='owner.ownerexperiencedetail', verbose_name='owner experience detail'),
        ),
    ]
