# Generated by Django 4.1.1 on 2022-09-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='keyword')),
            ],
            options={
                'verbose_name': 'keyword',
                'verbose_name_plural': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='WebsiteSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.CharField(max_length=255, verbose_name='meta description')),
                ('meta_author', models.CharField(max_length=255, verbose_name='meta author')),
                ('meta_title', models.CharField(max_length=255, verbose_name='meta title')),
                ('meta_keywords', models.ManyToManyField(to='website.keyword', verbose_name='meta keywords')),
            ],
            options={
                'verbose_name': 'website specification',
                'verbose_name_plural': 'website specifications',
            },
        ),
    ]
