# Generated by Django 4.1.1 on 2022-09-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitespecification',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, to='website.keyword', verbose_name='meta keywords'),
        ),
    ]
